#!/bin/ksh
set +x
# Date - 11/21/06
# Author - Donald Eytel
# Description - Send Message to a particular JMS iqmanager  Queue or Topic

ME=${0##*/}

function intMsgargs {
HOSTNAME="-h ${AUTOSYS_JMS_HOST}"
PORT="-p ${AUTOSYS_JMS_PORT}"
QSEND="-q jms.AutoSysTrigger"
CFNAME="-F jms.osbConnectionFactory"
TSEND=""
TIMEOUT=""
QRESPONSE="-Q jms.AutoSysResponse"
TRESPONSE=""
MESSAGE=""
SSL=""
USERNAME=""
PASSWORD=""
SLEEPTIME=""
set -A APARMS
}

intMsgargs
# Process Command Line Arguments
while getopts "::p:h:q:t:Q:T:m:a:z:S:U:P:f:F:s:" opt; do
   echo $opt
   case $opt in
       p ) PORT="-p $OPTARG";;
       h ) HOSTNAME="-h $OPTARG";;
       q ) QSEND="-q $OPTARG";;
       z ) TIMEOUT="-z $OPTARG";;
       Q ) QRESPONSE="-Q $OPTARG";;
       m ) MESSAGE="-m\"$OPTARG\"";;
       a ) APARMS="${APARMS} -a \"$OPTARG\" ";;
       f ) FNAME="$OPTARG";;
       F ) CFNAME="-F $OPTARG";;
       S ) SSL="-S $OPTARG";;
       U ) USERNAME="-U $OPTARG";;
       P ) PASSWORD="-P $OPTARG";;
       s ) SLEEPTIME="-s $OPTARG";;
      \? )
#           exit 201
           ;;
   esac
done


# Checking to see it we are sending to a TOPIC or QUEUE
SEND=""

if [[ -n "${QSEND}" ]] ; then
   SEND=${QSEND}
fi

# Checking to see if we are sending a Response Message to a TOPIC or QUEUE
RESPONSE=""

if [[ -n "${QRESPONSE}" ]] ; then
     RESPONSE=${QRESPONSE}
fi

# Get Message Arg Information 
# Defaulting TIMEOUT to 1 Day
if [[ -z "${TIMEOUT}" ]] ; then
TIMEOUT="-z 86400"
fi

if [[ -z "${AUTO_JOB_NAME}" ]] ; then
AUTO_JOB_NAME="DIRECT_COMMAND_LINE"
fi

if [[ -n "${FNAME}" ]] ; then
APARMS=""
source ${FNAME}
echo "APARMS=${APARMS}"
fi


print "\nExecuting sendMessage..."
echo "java -Xms3m -Xmx16m -jar /int2/scripts/tools/jmsClient/wlsJMSAutosys.jar ${PORT} ${HOSTNAME} ${SEND} ${RESPONSE} ${MESSAGE} -a AUTO_JOB_NAME=${AUTO_JOB_NAME} ${APARMS[*]} ${CFNAME} ${TIMEOUT} ${SSL} ${USERNAME} ${PASSWORD}"
eval java -Xms3m -Xmx16m -jar /int2/scripts/tools/jmsClient/wlsJMSAutosys.jar ${PORT} ${HOSTNAME} ${SEND} ${RESPONSE} ${MESSAGE} -a AUTO_JOB_NAME=${AUTO_JOB_NAME} ${APARMS[*]} ${CFNAME} ${TIMEOUT} ${SSL} ${USERNAME} ${PASSWORD} 
EXITCODE=$?
if [[ ${EXITCODE} -ne 0 ]] ; then
   print "\nsendMessage unsuccessful."
   exit ${EXITCODE} 
else
if [[ -z "${SLEEPTIME}" ]] ; then
   print "Sleeping $SLEEPTIME"
   sleep $SLEEPTIME
fi   
   print "\nsendMessage successful."
   exit 0
fi
