<?binding.jca CommonserviceErrorProcConfigDB_1.00_db.jca?><wsdl:definitions name="CommonserviceErrorProcConfigDB_1.00" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NikeStub/DBAdapter_ErrorService/CommonserviceErrorProcConfigDB_1_00" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NikeStub/DBAdapter_ErrorService/CommonserviceErrorProcConfigDB_1_00" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CommonserviceErrorProcConfigDB_1/00">
    <plt:partnerLinkType name="CommonserviceErrorProcConfigDB_1.00_plt">
        <plt:role name="CommonserviceErrorProcConfigDB_1.00_role">
            <plt:portType name="tns:CommonserviceErrorProcConfigDB_1.00_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CommonserviceErrorProcConfigDB_1/00" schemaLocation="../schemas/CommonserviceErrorProcDBAdpXsd_1.00.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MiddlewareCommonErrorCollection_msg">
        <wsdl:part name="MiddlewareCommonErrorCollection" element="top:MiddlewareCommonErrorCollection"/>
    </wsdl:message>
    <wsdl:portType name="CommonserviceErrorProcConfigDB_1.00_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:MiddlewareCommonErrorCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>