<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NikeStub/DBAdapter_ErrorService/CommonserviceErrorProcConfigDB_1_00" name="CommonserviceErrorProcConfigDB_1.00-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NikeStub/DBAdapter_ErrorService/CommonserviceErrorProcConfigDB_1_00" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NikeStub/DBAdapter_ErrorService/CommonserviceErrorProcConfigDB_1_00" location="CommonserviceErrorProcConfigDB_1_00.wsdl"/>
  <binding name="CommonserviceErrorProcConfigDB_1.00_ptt-binding" type="tns:CommonserviceErrorProcConfigDB_1.00_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="CommonserviceErrorProcConfigDB_1.00-service">
    <port name="CommonserviceErrorProcConfigDB_1.00-port" binding="tns:CommonserviceErrorProcConfigDB_1.00_ptt-binding">
      <soap:address location="jca://eis/DB/iccIR_comsvc"/>
    </port>
  </service>
</definitions>