<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application3/Project1/AuditServiceDBAdp" name="AuditServiceDBAdp-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Application3/Project1/AuditServiceDBAdp" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Application3/Project1/AuditServiceDBAdp" location="../resources/wsdls/AuditService_DB_Write_1.00.wsdl"/>
  <binding name="AuditServiceDBAdp_ptt-binding" type="tns:AuditServiceDBAdp_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="AuditServiceDBAdp-service">
    <port name="AuditServiceDBAdp-port" binding="tns:AuditServiceDBAdp_ptt-binding">
      <soap:address location="jca://eis/DB/osbAudit"/>
    </port>
  </service>
</definitions>