<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CommonserviceLogProcFileRollOver_1.00/Project1/CommonserviceAlertProcDBPoll_1_00" name="CommonserviceAlertProcDBPoll_1.00-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CommonserviceLogProcFileRollOver_1.00/Project1/CommonserviceAlertProcDBPoll_1_00" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CommonserviceLogProcFileRollOver_1.00/Project1/CommonserviceAlertProcDBPoll_1_00" location="CommonserviceAlertProcDBPoll_1_00.wsdl"/>
  <binding name="CommonserviceAlertProcDBPoll_1.00_ptt-binding" type="tns:CommonserviceAlertProcDBPoll_1.00_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="receive">
      <soap:operation soapAction="receive"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="CommonserviceAlertProcDBPoll_1.00-service">
    <port name="CommonserviceAlertProcDBPoll_1.00-port" binding="tns:CommonserviceAlertProcDBPoll_1.00_ptt-binding">
      <soap:address location="jca://eis/DB/iccIR_comsvcXA"/>
    </port>
  </service>
</definitions>