<wsdl:definitions name="CommonserviceAlertProcPS_1_00" targetNamespace="http://xmlns.oracle.com/CommonserviceLogProcFileRollOver_1_00/Project2/CommonserviceAlertProcPS_1_00" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/CommonserviceLogProcFileRollOver_1_00/Project2/CommonserviceAlertProcPS_1_00" xmlns:ns1="http://www.xmlns.nike.com/enterprise/resources/xsd/alert/v1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	TYPE DEFINITION - List of services participating in this BPEL process
	The default output of the BPEL designer uses strings as input and 
	output to the BPEL Process. But you can define or import any XML 
	Schema type and use them as part of the message types.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->   
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.xmlns.nike.com/enterprise/resources/xsd/alert/v1" schemaLocation="../../../../../CommonServiceInterfaces/src/osb/resources/schemas/AlertMessageXSD_1.00.xsd"/>
		</schema>
	</wsdl:types>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	MESSAGE TYPE DEFINITION - Definition of the message types used as 
	part of the port type defintions
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->      
	<wsdl:message name="CommonserviceAlertProcPS_1_00RequestMessage">
		<wsdl:part name="payload" element="ns1:AlertMessage"/>
	</wsdl:message>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PORT TYPE DEFINITION - A port type groups a set of operations into
	a logical service unit.
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

	<!-- portType implemented by the CommonserviceAlertProcPS_1_00 BPEL process -->
	<wsdl:portType name="CommonserviceAlertProcPS_1_00">
		<wsdl:operation name="process">
			<wsdl:input message="client:CommonserviceAlertProcPS_1_00RequestMessage"/>
		</wsdl:operation>
	</wsdl:portType>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	PARTNER LINK TYPE DEFINITION
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ --> 
	<plnk:partnerLinkType name="CommonserviceAlertProcPS_1_00">
		<plnk:role name="CommonserviceAlertProcPS_1_00Provider">
			<plnk:portType name="client:CommonserviceAlertProcPS_1_00"/>
		</plnk:role>
	</plnk:partnerLinkType>
	<wsdl:binding name="CommonServiceAlertProc_ProxyBinding" type="client:CommonserviceAlertProcPS_1_00">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="process">
			<soap:operation soapAction="http://xmlns.oracle.com/CommonserviceLogProcFileRollOver_1_00/Project2/CommonserviceAlertProcPS_1_00/process"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CommonServiceAlertProc_ProxyService">
		<wsdl:port name="NewPort" binding="client:CommonServiceAlertProc_ProxyBinding">
			<soap:address location="http://www.example.org/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>