<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/NikeFetAdapters/CommonserviceLogProcConfigDB_1_00/LogConfigDB_1_00" name="LogConfigDB_1.00-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/NikeFetAdapters/CommonserviceLogProcConfigDB_1_00/LogConfigDB_1_00" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/NikeFetAdapters/CommonserviceLogProcConfigDB_1_00/LogConfigDB_1_00" location="LogConfigDB_1_00.wsdl"/>
  <binding name="LogConfigDB_1_00_ptt-binding" type="tns:LogConfigDB_1_00_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="LogConfigDB_1.00">
      <soap:operation soapAction="LogConfigDB_1.00"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="LogConfigDB_1.00-service">
    <port name="LogConfigDB_1.00-port" binding="tns:LogConfigDB_1_00_ptt-binding">
      <soap:address location="jca://eis/DB/iccIR_comsvc"/>
    </port>
  </service>
</definitions>