<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Nike_Adapters/Nike_Adapters/CommonserviceLogProcLogWrite_1_00" name="CommonserviceLogProcLogWrite_1.00-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Nike_Adapters/Nike_Adapters/CommonserviceLogProcLogWrite_1_00" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/file/Nike_Adapters/Nike_Adapters/CommonserviceLogProcLogWrite_1_00" location="LogWrite_1.00.wsdl"/>
  <binding name="Write_ptt-binding" type="tns:Write_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="Write">
      <soap:operation soapAction="Write"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="CommonserviceLogProcLogWrite_1.00-service">
    <port name="CommonserviceLogProcLogWrite_1.00-port" binding="tns:Write_ptt-binding">
      <soap:address location="jca://eis/FileAdapter"/>
    </port>
  </service>
</definitions>