<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/Error_Processing_Service/Error_Processing_Service_File_Reader/Errorhandler_Processor_Read_FileAdp_1_00" name="Errorhandler_Processor_Read_FileAdp_1.00-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Error_Processing_Service/Error_Processing_Service_File_Reader/Errorhandler_Processor_Read_FileAdp_1_00" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/file/Error_Processing_Service/Error_Processing_Service_File_Reader/Errorhandler_Processor_Read_FileAdp_1_00" location="Errorhandler_Processor_Read_FileAdp_1.00.wsdl"/>
  <binding name="Read_ptt-binding" type="tns:Read_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="Read">
      <soap:operation soapAction="Read"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="Errorhandler_Processor_Read_FileAdp_1.00-service">
    <port name="Errorhandler_Processor_Read_FileAdp_1.00-port" binding="tns:Read_ptt-binding">
      <soap:address location="jca://eis/FileAdapter"/>
    </port>
  </service>
</definitions>