<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/appReadMultiFile/prjReadMultiFile/AuditDB" name="AuditDB-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/appReadMultiFile/prjReadMultiFile/AuditDB" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/appReadMultiFile/prjReadMultiFile/AuditDB" location="AuditService_DB_Write_1.01.wsdl"/>
  <binding name="AuditDB_ptt-binding" type="tns:AuditDB_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="merge">
      <soap:operation soapAction="merge"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="AuditDB-service">
    <port name="AuditDB-port" binding="tns:AuditDB_ptt-binding">
      <soap:address location="jca://eis/DB/osbAudit"/>
    </port>
  </service>
</definitions>