<wsdl:definitions name="MatchingPORequest" targetNamespace="urn:com:nike:orders:1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:inp1="urn:com:nike:orders" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:com:nike:orders:1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:com:nike:orders" schemaLocation="../schemas/DOMS_MatchingPO_1037_SCS_XsdSrc_1.00.xsd"/>
        </xsd:schema>
    </wsdl:types>
	<wsdl:message name="requestMessage">
        <wsdl:part name="Request" element="inp1:POCreateOrder"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Response" element="inp1:MatchingPOResponse"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="Fault" element="inp1:MatchingPOFault"/>
    </wsdl:message>
    <wsdl:portType name="MatchingPORequestPortType">
        <wsdl:operation name="publish">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="MatchingPORequestfault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="MatchingPORequestBinding" type="tns:MatchingPORequestPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="publish">
            <soap:operation style="document" soapAction="http://xmlns.oracle.com/deliver/order/MatchingPORequestOPReq"/>
            <wsdl:input>
                <soap:body use="literal" parts="Request"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="Response"/>
            </wsdl:output>
            <wsdl:fault name="MatchingPORequestfault">
                <soap:fault name="MatchingPORequestfault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="MatchingPORequestService">
        <wsdl:port name="MatchingPORequestPortType" binding="tns:MatchingPORequestBinding">
            <soap:address location="http://!!osb.http.loadbalancer!!/deliver/order/MatchingPORequest"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>